### PR TITLE
Update generate.py

### PR DESCRIPTION
**Pull request by SilentJMA**
Function Decomposition: The code has been divided into functions with clear responsibilities, making it more modular and easier to read.

Data Flow: The flow of data has been improved by separating data retrieval, data extraction, and README generation into separate functions.

Readability: Variable and function names have been updated to be more descriptive.

Code Comments: While not included in this code, consider adding comments to further explain specific sections or logic if needed.

Error Handling: You might want to add error handling for cases where network requests fail or regular expressions don't match to make the script more robust.

### CODE REVIEW

**Review by Sigmanificient — APPROVED** [review]

**Comment by SilentJMA** [comment]
It can be merged

**Comment by SilentJMA** [comment]
Good luck

**Comment by SilentJMA** [comment]
you can merge it and good luck

**Comment by Sigmanificient** [comment]
Thanks for taking the time to improve my little script
I take a look back at that repo and it inspired me to update it a bit

**Pull request merged**
